bin/bash
export STORM_DIRNAME=$PARCELS_ROOT/$PARCEL_DIRNAME/storm-0.9.4
export KAFKA_MANAGER_DIRNAME=$PARCELS_ROOT/$PARCEL_DIRNAME/kafka-manager-1.2.7
export MONGODB_DIRNAME=$PARCELS_ROOT/$PARCEL_DIRNAME/mongodb-3.0.15
